In [1]:
import pandas as pd
import numpy as np

In [2]:
departments = pd.read_csv("Data/departments.csv")
diagnosis = pd.read_csv("Data/diagnosis.csv")
encounters = pd.read_csv("Data/encounters.csv")
patients = pd.read_csv("Data/patients.csv")
providers = pd.read_csv("Data/providers.csv")
social_determinants = pd.read_csv("Data/social_determinants.csv")
tigercensuscodes = pd.read_csv("Data/tigercensuscodes.csv")

/var/folders/r9/mhc5twwx0blgr6rw0wr28jmc0000gn/T/ipykernel_72885/2207771560.py:6: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  social_determinants = pd.read_csv("Data/social_determinants.csv")

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [10]:
data2  = pd.read_csv("Data/output2.csv")

In [11]:
data2.columns

Index(['PatientDurableKey', 'IndexEncounterKey', 'FirstOutpatientDate',
       'IndexYear', 'IndexMonth', 'IndexDayOfWeek', 'IndexDepartmentKey',
       'IndexDepartmentName', 'IndexDepartmentType',
       'IndexDepartmentSpecialty', 'IndexDepartmentCity',
       'IndexDepartmentCounty', 'IndexDepartmentPostalCode',
       'IndexDepartmentCensusTract', 'IndexDiagnosisName',
       'IndexDiagnosisValue', 'IndexGroupCode', 'IndexGroupName',
       'IndexAdmissionSource', 'IndexAdmissionType', 'IndexVisitType',
       'IndexVisitTypeDescription', 'CensusBlockGroupFipsCode', 'FirstRace',
       'MaritalStatus', 'MyChartStatus', 'OmbEthnicity', 'OmbRace',
       'PatientBirthYearBin', 'SexAssignedAtBirth', 'SexualOrientation',
       'SmokingStatus', 'VitalStatus', 'ClinicianTitle', 'PrimaryDepartment',
       'PrimarySpecialty', 'OfficeCity', 'OfficePostalCode', 'DataEndDate',
       'DaysObservedAfterIndex', 'SecondOutpatientDate',
       'DaysBetweenFirstSecond', 'FirstEDDate', 'DaysUntilED',
       'FirstInpatientDate', 'DaysUntilInpatient', 'isBroken', 'isAcute',
       'DaysSincePrevEncounter', 'DaysSincePrevDiabetesEncounter',
       'PriorEncounters180', 'PriorOutpatient180', 'PriorED180',
       'PriorInpatient180', 'PriorDiabetes180', 'PriorDistinctDepartments180',
       'PriorEncounters365', 'PriorED365', 'PriorInpatient365',
       'PriorDiabetes365', 'HasAnySDOHAtIndex', 'PatientLat', 'PatientLon',
       'DeptLat', 'DeptLon', 'DistanceMilesToIndexDept'],
      dtype='object')

In [15]:
drop_cols = [
    "PatientDurableKey",
    "IndexEncounterKey",
    "FirstOutpatientDate",
    "IndexDiagnosisName",
    "IndexDiagnosisValue",
    "IndexGroupCode",
    "IndexGroupName",
    "DataEndDate",
    "DaysObservedAfterIndex",
    "SecondOutpatientDate",
    "DaysBetweenFirstSecond",
    "FirstEDDate",
    "DaysUntilED",
    "FirstInpatientDate",
    "DaysUntilInpatient",
    "isAcute",
    "DaysSincePrevDiabetesEncounter",
    "DaysSincePrevEncounter",
    "PriorEncounters180",
    "PriorOutpatient180",
    "PriorED180",
    "PriorInpatient180",
    "PriorDiabetes180",
    "PriorDistinctDepartments180",
    "PriorEncounters365",
    "PriorED365",
    "PriorInpatient365",
    "PriorDiabetes365",
    "HasAnySDOHAtIndex",
    "PatientLon",
    "DeptLat",
    "DeptLon",
    "PatientLat"

]

model_df = data2.drop(columns=drop_cols)

In [16]:
model_df.shape

(20331, 33)

In [17]:
print(model_df.isna().sum().sort_values(ascending=False).to_string())

DistanceMilesToIndexDept      7779
IndexDepartmentCensusTract    1916
FirstRace                     1426
PatientBirthYearBin           1046
MyChartStatus                 1045
OmbEthnicity                  1045
SexAssignedAtBirth            1045
MaritalStatus                 1045
SexualOrientation             1045
CensusBlockGroupFipsCode      1045
SmokingStatus                 1045
VitalStatus                   1045
OmbRace                       1045
PrimarySpecialty                28
OfficeCity                       3
OfficePostalCode                 3
IndexAdmissionSource             1
IndexAdmissionType               1
ClinicianTitle                   0
PrimaryDepartment                0
isBroken                         0
IndexDepartmentKey               0
IndexDepartmentName              0
IndexMonth                       0
IndexVisitTypeDescription        0
IndexVisitType                   0
IndexDayOfWeek                   0
IndexDepartmentPostalCode        0
IndexDepartmentCounty            0
IndexDepartmentCity              0
IndexDepartmentSpecialty         0
IndexDepartmentType              0
IndexYear                        0

In [21]:
model_df = model_df.drop(columns=["IndexDepartmentCensusTract", "CensusBlockGroupFipsCode"])

In [18]:
model_df["DistanceMilesToIndexDept"] = model_df["DistanceMilesToIndexDept"].fillna(
    model_df["DistanceMilesToIndexDept"].median()
)

In [22]:
print(model_df.isna().sum().sort_values(ascending=False).to_string())

FirstRace                    1426
PatientBirthYearBin          1046
MaritalStatus                1045
VitalStatus                  1045
MyChartStatus                1045
SexAssignedAtBirth           1045
SexualOrientation            1045
OmbRace                      1045
SmokingStatus                1045
OmbEthnicity                 1045
PrimarySpecialty               28
OfficeCity                      3
OfficePostalCode                3
IndexAdmissionSource            1
IndexAdmissionType              1
ClinicianTitle                  0
PrimaryDepartment               0
isBroken                        0
IndexYear                       0
IndexMonth                      0
IndexVisitTypeDescription       0
IndexVisitType                  0
IndexDepartmentPostalCode       0
IndexDepartmentCounty           0
IndexDepartmentCity             0
IndexDepartmentSpecialty        0
IndexDepartmentType             0
IndexDepartmentName             0
IndexDepartmentKey              0
IndexDayOfWeek                  0
DistanceMilesToIndexDept        0

In [23]:
model_df_complete = model_df.dropna()

In [24]:
model_df_complete.shape

(18876, 31)

In [25]:
model_df_complete["isBroken"].value_counts(normalize=True, dropna=False)

isBroken
1    0.537455
0    0.462545
Name: proportion, dtype: float64

In [26]:
missing_tokens = ["*Unknown", "Unknown", "None", "", "NaN", "*Not Applicable", "*Unspecified"]

model_clean = model_df_complete.replace(missing_tokens, "Missing")

In [32]:
model_clean.sample(10)

,IndexYear,IndexMonth,IndexDayOfWeek,IndexDepartmentKey,IndexDepartmentName,IndexDepartmentType,IndexDepartmentSpecialty,IndexDepartmentCity,IndexDepartmentCounty,IndexDepartmentPostalCode,IndexAdmissionSource,IndexAdmissionType,IndexVisitType,IndexVisitTypeDescription,FirstRace,MaritalStatus,MyChartStatus,OmbEthnicity,OmbRace,PatientBirthYearBin,SexAssignedAtBirth,SexualOrientation,SmokingStatus,VitalStatus,ClinicianTitle,PrimaryDepartment,PrimarySpecialty,OfficeCity,OfficePostalCode,isBroken,DistanceMilesToIndexDept
3401,2022,2,1,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,Black or African American,Divorced,Activated,Not Hispanic or Latino,Black or African American,1950.0,Female,Missing,Former,Alive,Missing,Missing,Missing,Missing,Missing,0,3.698227
8295,2022,6,5,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,NEW PATIENT,Clinic Visits- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1965.0,Missing,Missing,Former,Alive,Missing,Missing,Missing,Missing,Missing,1,4.409723
8712,2022,7,3,834,CORPORATE VIEW CLINIC,Missing,Family Medicine,TOPEKA,SHAWNEE,66615-1245,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Widowed,Activated,Not Hispanic or Latino,White,1935.0,Missing,Missing,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,4.693631
10479,2022,10,2,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1945.0,Missing,Choose not to disclose,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,3.460727
13089,2023,5,5,358,901 FAMILY PRACTICE,Missing,Family Medicine,Topeka,SHAWNEE,66606,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Married,Activated,Asked but No Answer,White,1960.0,Missing,Missing,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,4.212026
9914,2022,9,4,10282,ASBURY CLINIC,Missing,Primary Care,TOPEKA,SHAWNEE,66614-4466,Missing,Missing,OFFICE VISIT,Clinic Visit- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1960.0,Female,Straight,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,4.693631
2022,2022,2,3,478,NORTH FIELDING CLINIC,Missing,Family Medicine,TOPEKA,SHAWNEE,66618,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1965.0,Missing,Missing,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,3.225653
18052,2024,8,3,10282,ASBURY CLINIC,Missing,Primary Care,TOPEKA,SHAWNEE,66614-4466,Missing,Missing,FOLLOW UP,Clinic Visits- In Person,White or Caucasian,Divorced,Activated,Not Hispanic or Latino,White,1960.0,Missing,Missing,Every Day,Alive,Missing,Missing,Missing,Missing,Missing,0,4.693631
10270,2022,10,3,299,6TH FRAZIER ENDOCRINOLOGY,Missing,Endocrinology,Topeka,SHAWNEE,66606,Missing,Missing,NEW PATIENT,Clinic Visits- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1945.0,Missing,Missing,Every Day,Alive,Missing,Missing,Missing,Missing,Missing,0,4.693631
16716,2024,4,2,10282,ASBURY CLINIC,Missing,Primary Care,TOPEKA,SHAWNEE,66614-4466,Missing,Missing,OFFICE VISIT,Clinic Visit- In Person,White or Caucasian,Married,Activated,Not Hispanic or Latino,White,1985.0,Missing,Missing,Never,Alive,Missing,Missing,Missing,Missing,Missing,0,4.693631

In [28]:
model_clean.to_csv("cleaned_data.csv", index = False)

In [33]:
cleaned_data = pd.read_csv("Data/cleaned_data.csv")

In [37]:
y = cleaned_data["isBroken"]

cleaned_data = cleaned_data.drop(columns=[
    "IndexDepartmentKey",
    "IndexDepartmentPostalCode",
    "PrimaryDepartment",
    "OfficeCity",
    "OfficePostalCode",
    "isBroken"
])

In [43]:
cleaned_data.dtypes.reset_index()

                        index               0
0                   IndexYear           int64
1                  IndexMonth           int64
2              IndexDayOfWeek           int64
3         IndexDepartmentName          object
4         IndexDepartmentType          object
5    IndexDepartmentSpecialty          object
6         IndexDepartmentCity          object
7       IndexDepartmentCounty          object
8        IndexAdmissionSource          object
9          IndexAdmissionType          object
10             IndexVisitType          object
11  IndexVisitTypeDescription          object
12                  FirstRace          object
13              MaritalStatus          object
14              MyChartStatus          object
15               OmbEthnicity          object
16                    OmbRace          object
17        PatientBirthYearBin  string[python]
18         SexAssignedAtBirth          object
19          SexualOrientation          object
20              SmokingStatus          object
21                VitalStatus          object
22             ClinicianTitle          object
23           PrimarySpecialty          object
24   DistanceMilesToIndexDept         float64

In [41]:
cleaned_data["PatientBirthYearBin"] = cleaned_data["PatientBirthYearBin"].astype("Int64").astype("string")

In [44]:
for col in ["IndexDepartmentCity", "IndexDepartmentSpecialty", "IndexDepartmentCounty"]:
    cleaned_data[col] = cleaned_data[col].astype("string").str.upper()

### CLEANED DATA FROM HERE
###
###
###
###

In [73]:
from pathlib import Path
import pandas as pd

path = Path("Data")
path.mkdir(exist_ok=True)

df = pd.read_csv("cleaned_data.csv")
y = df["isBroken"]

X = df.drop(columns=[
    "IndexDepartmentKey",
    "IndexDepartmentPostalCode",
    "PrimaryDepartment",
    "OfficeCity",
    "OfficePostalCode",
    "isBroken",
    "PrimarySpecialty",
    "ClinicianTitle",
    "SexualOrientation",
    "SexAssignedAtBirth",
    "IndexAdmissionType",
    "IndexAdmissionSource",
    "IndexDepartmentType"
]).copy()

X["IndexDepartmentCity"] = X["IndexDepartmentCity"].astype("string").str.upper()

def clean_visit_type(x):
    if pd.isna(x):
        return "unknown"
    x = str(x).lower().strip()

    if "clinic" in x and "virtual" in x:
        return "clinic_virtual"
    if "clinic" in x:
        return "clinic_in_person"
    if "lab" in x:
        return "lab"
    if "ultrasound" in x or "imaging" in x:
        return "imaging"
    if "procedure" in x:
        return "procedures"
    if "admission" in x:
        return "pre_admission"
    return "other"

X["IndexVisitTypeDescription"] = X["IndexVisitTypeDescription"].apply(clean_visit_type)

print("IndexDepartmentType in X?", "IndexDepartmentType" in X.columns)
print("X shape:", X.shape)

IndexDepartmentType in X? False
X shape: (18876, 18)

In [74]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_model.select_dtypes(include=["number", "bool"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])

enet_model = Pipeline([
    ("prep", preprocessor),
    ("clf", LogisticRegressionCV(
        penalty="elasticnet",
        solver="saga",
        cv=5,
        scoring="accuracy",
        Cs=[0.01, 0.1, 1, 10],
        l1_ratios=[0.2, 0.5, 0.8],
        max_iter=5000,
        n_jobs=-1,
        random_state=42
    ))
])

X_train, X_test, y_train, y_test = train_test_split(
    X_model, y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

enet_model.fit(X_train, y_train)

y_pred = enet_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

clf = enet_model.named_steps["clf"]
print("\nBest C:", clf.C_[0])
print("Best l1_ratio:", clf.l1_ratio_[0])

Accuracy: 0.6761122881355932

Classification report:

              precision    recall  f1-score   support

           0       0.70      0.52      0.60      1747
           1       0.66      0.81      0.73      2029

    accuracy                           0.68      3776
   macro avg       0.68      0.67      0.66      3776
weighted avg       0.68      0.68      0.67      3776

Confusion matrix:
 [[ 910  837]
 [ 386 1643]]

Best C: 0.1
Best l1_ratio: 0.8

In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

# final training data
X_final = X.copy()
y_final = y.copy()

cat_cols = X_final.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_final.select_dtypes(include=["number", "bool"]).columns.tolist()

final_preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])

final_model = Pipeline([
    ("prep", final_preprocessor),
    ("clf", LogisticRegression(
        penalty="elasticnet",
        solver="saga",
        C=0.1,
        l1_ratio=0.8,
        max_iter=5000,
        random_state=42
    ))
])

final_model.fit(X_final, y_final)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['IndexYear', 'IndexMonth',
                                                   'IndexDayOfWeek',
                                                   'PatientBirthYearBin',
                                                   'DistanceMilesToIndexDept']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['IndexDepartmentName',
                                                   'IndexDepartmentSpecialty',
                                                   'IndexDepartmentCity',
                                                   'IndexDepartmentCounty',
                                                   'IndexVisitType',
                                                   'IndexVisitTypeDescription',
                                                   'FirstRace', 'MaritalStatus',
                                                   'MyChartStatus',
                                                   'OmbEthnicity', 'OmbRace',
                                                   'SmokingStatus',
                                                   'VitalStatus'])])),
                ('clf',
                 LogisticRegression(C=0.1, l1_ratio=0.8, max_iter=5000,
                                    penalty='elasticnet', random_state=42,
                                    solver='saga'))])

In [77]:
feature_names = final_model.named_steps["prep"].get_feature_names_out()
coefs = final_model.named_steps["clf"].coef_[0]

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefs,
    "abs_coefficient": np.abs(coefs)
}).sort_values("abs_coefficient", ascending=False)

print(coef_df.head(30).to_string(index=False))

                                                      feature  coefficient  abs_coefficient
                     cat__IndexDepartmentSpecialty_Wound Care    -1.588885         1.588885
                  cat__IndexDepartmentSpecialty_Endocrinology    -0.886371         0.886371
                                 cat__IndexVisitType_PHYSICAL     0.864250         0.864250
                             cat__IndexDepartmentCounty_OSAGE     0.556888         0.556888
           cat__IndexDepartmentName_6TH FRAZIER ENDOCRINOLOGY    -0.472006         0.472006
                           cat__IndexVisitType_WELLNESS VISIT     0.408773         0.408773
               cat__IndexDepartmentName_FHC INTERNAL MEDICINE    -0.371385         0.371385
                                cat__IndexVisitType_FOLLOW UP     0.289811         0.289811
                                  cat__IndexVisitType_CONSULT    -0.273559         0.273559
                        cat__IndexDepartmentName_CROCO CLINIC     0.249658         0.249658
                              cat__IndexDepartmentCity_TOPEKA     0.249054         0.249054
                      cat__IndexDepartmentName_823 NEPHROLOGY     0.225517         0.225517
                            cat__IndexDepartmentSpecialty_Lab     0.222021         0.222021
                                      cat__IndexVisitType_LAB     0.222021         0.222021
                                   cat__MaritalStatus_Missing     0.211706         0.211706
                       cat__IndexDepartmentName_823 WOUNDCARE    -0.208837         0.208837
                                       cat__VitalStatus_Alive     0.203760         0.203760
                       cat__IndexDepartmentName_ASBURY CLINIC     0.191878         0.191878
                cat__IndexDepartmentSpecialty_Family Medicine     0.169093         0.169093
cat__IndexDepartmentName_6TH FRAZIER DIABETES LEARNING CENTER    -0.164887         0.164887
                        cat__IndexVisitType_HOSP/ER FOLLOW UP    -0.162455         0.162455
              cat__IndexVisitTypeDescription_clinic_in_person    -0.160012         0.160012
                                              num__IndexMonth     0.159844         0.159844
                      cat__IndexDepartmentSpecialty_Neurology    -0.154020         0.154020
                                 cat__MyChartStatus_Activated    -0.151644         0.151644
                                     num__PatientBirthYearBin    -0.138436         0.138436
                 cat__IndexDepartmentName_901 FAMILY PRACTICE     0.137638         0.137638
                 cat__IndexDepartmentName_823 FAMILY PRACTICE    -0.132644         0.132644
                                               num__IndexYear     0.124737         0.124737
                             cat__IndexDepartmentCity_MERIDEN     0.110339         0.110339

In [78]:
from sklearn.metrics import roc_auc_score

y_prob = enet_model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_prob)

print("ROC AUC:", roc_auc)

ROC AUC: 0.7185228891999043

In [79]:
cat_cols = X_final.select_dtypes(include=["object", "string", "category"]).columns.tolist()
cat_cols_sorted = sorted(cat_cols, key=len, reverse=True)

def original_variable_name(feat):
    if feat.startswith("num__"):
        return feat.replace("num__", "", 1)
    if feat.startswith("cat__"):
        rest = feat.replace("cat__", "", 1)
        for col in cat_cols_sorted:
            if rest == col or rest.startswith(col + "_"):
                return col
        return rest
    return feat

coef_df["original_variable"] = coef_df["feature"].apply(original_variable_name)

var_importance = (
    coef_df.groupby("original_variable", as_index=False)
    .agg(
        sum_abs_coefficient=("abs_coefficient", "sum"),
        max_abs_coefficient=("abs_coefficient", "max"),
        n_levels=("feature", "count")
    )
    .sort_values("sum_abs_coefficient", ascending=False)
)

print(var_importance.to_string(index=False))

        original_variable  sum_abs_coefficient  max_abs_coefficient  n_levels
 IndexDepartmentSpecialty             3.343355             1.588885        34
      IndexDepartmentName             2.570048             0.472006       104
           IndexVisitType             2.317980             0.864250       116
    IndexDepartmentCounty             0.783894             0.556888        10
      IndexDepartmentCity             0.539031             0.249054        12
            MaritalStatus             0.337687             0.211706         9
IndexVisitTypeDescription             0.219907             0.160012         7
              VitalStatus             0.203760             0.203760         2
            MyChartStatus             0.178019             0.151644         5
               IndexMonth             0.159844             0.159844         1
                  OmbRace             0.142030             0.079524         9
      PatientBirthYearBin             0.138436             0.138436         1
                IndexYear             0.124737             0.124737         1
            SmokingStatus             0.082691             0.070507         9
             OmbEthnicity             0.080886             0.040998         4
 DistanceMilesToIndexDept             0.044473             0.044473         1
                FirstRace             0.017297             0.011733        10
           IndexDayOfWeek             0.008774             0.008774         1

In [81]:
var_importance = (
    coef_df.groupby("original_variable", as_index=False)
    .agg(
        sum_abs_coefficient=("abs_coefficient", "sum"),
        mean_abs_coefficient=("abs_coefficient", "mean"),
        max_abs_coefficient=("abs_coefficient", "max"),
        n_levels=("feature", "count")
    )
)

print("Sorted by mean absolute coefficient:\n")
print(
    var_importance
    .sort_values("mean_abs_coefficient", ascending=False)
    .to_string(index=False)
)

Sorted by mean absolute coefficient:

        original_variable  sum_abs_coefficient  mean_abs_coefficient  max_abs_coefficient  n_levels
               IndexMonth             0.159844              0.159844             0.159844         1
      PatientBirthYearBin             0.138436              0.138436             0.138436         1
                IndexYear             0.124737              0.124737             0.124737         1
              VitalStatus             0.203760              0.101880             0.203760         2
 IndexDepartmentSpecialty             3.343355              0.098334             1.588885        34
    IndexDepartmentCounty             0.783894              0.078389             0.556888        10
      IndexDepartmentCity             0.539031              0.044919             0.249054        12
 DistanceMilesToIndexDept             0.044473              0.044473             0.044473         1
            MaritalStatus             0.337687              0.037521             0.211706         9
            MyChartStatus             0.178019              0.035604             0.151644         5
IndexVisitTypeDescription             0.219907              0.031415             0.160012         7
      IndexDepartmentName             2.570048              0.024712             0.472006       104
             OmbEthnicity             0.080886              0.020222             0.040998         4
           IndexVisitType             2.317980              0.019983             0.864250       116
                  OmbRace             0.142030              0.015781             0.079524         9
            SmokingStatus             0.082691              0.009188             0.070507         9
           IndexDayOfWeek             0.008774              0.008774             0.008774         1
                FirstRace             0.017297              0.001730             0.011733        10

In [83]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

# -------------------------
# data
# -------------------------
X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_model.select_dtypes(include=["number", "bool"]).columns.tolist()

# -------------------------
# preprocessing
# -------------------------
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])

# -------------------------
# train / test split
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

# -------------------------
# pipeline
# -------------------------
xgb_pipe = Pipeline([
    ("prep", preprocessor),
    ("clf", XGBClassifier(
        objective="binary:logistic",
        eval_metric="auc",
        random_state=42,
        n_jobs=-1
    ))
])

# -------------------------
# small tuning grid
# -------------------------
param_grid = {
    "clf__n_estimators": [100, 200],
    "clf__max_depth": [3, 5],
    "clf__learning_rate": [0.05, 0.1],
    "clf__subsample": [0.8, 1.0],
    "clf__colsample_bytree": [0.8, 1.0]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid = GridSearchCV(
    estimator=xgb_pipe,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

# fit
grid.fit(X_train, y_train)

# best model
best_xgb = grid.best_estimator_

# evaluate on test set
y_prob = best_xgb.predict_proba(X_test)[:, 1]
y_pred = best_xgb.predict(X_test)

print("Best params:", grid.best_params_)
print("Best CV ROC AUC:", grid.best_score_)
print("Test ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 32 candidates, totalling 160 fits
Best params: {'clf__colsample_bytree': 0.8, 'clf__learning_rate': 0.05, 'clf__max_depth': 5, 'clf__n_estimators': 100, 'clf__subsample': 0.8}
Best CV ROC AUC: 0.7287071119253066
Test ROC AUC: 0.7281796605206193

Classification report:

              precision    recall  f1-score   support

           0       0.71      0.51      0.59      1747
           1       0.66      0.83      0.73      2029

    accuracy                           0.68      3776
   macro avg       0.69      0.67      0.66      3776
weighted avg       0.69      0.68      0.67      3776

Confusion matrix:
 [[ 889  858]
 [ 355 1674]]

In [84]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_model.select_dtypes(include=["number", "bool"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])

X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

xgb_pipe = Pipeline([
    ("prep", preprocessor),
    ("clf", XGBClassifier(
        objective="binary:logistic",
        eval_metric="auc",
        random_state=42,
        n_jobs=-1
    ))
])

param_grid = {
    "clf__n_estimators": [75, 100, 125],
    "clf__max_depth": [4, 5, 6],
    "clf__learning_rate": [0.03, 0.05, 0.07],
    "clf__subsample": [0.7, 0.8, 0.9],
    "clf__colsample_bytree": [0.7, 0.8, 0.9],
    "clf__min_child_weight": [1, 3, 5],
    "clf__gamma": [0, 0.1, 0.3]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid2 = GridSearchCV(
    estimator=xgb_pipe,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

grid2.fit(X_train, y_train)

best_xgb_2 = grid2.best_estimator_

y_prob = best_xgb_2.predict_proba(X_test)[:, 1]
y_pred = best_xgb_2.predict(X_test)

print("Best params:", grid2.best_params_)
print("Best CV ROC AUC:", grid2.best_score_)
print("Test ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 2187 candidates, totalling 10935 fits
Best params: {'clf__colsample_bytree': 0.7, 'clf__gamma': 0.1, 'clf__learning_rate': 0.05, 'clf__max_depth': 5, 'clf__min_child_weight': 1, 'clf__n_estimators': 125, 'clf__subsample': 0.7}
Best CV ROC AUC: 0.7289361019250272
Test ROC AUC: 0.7278584734289268

Classification report:

              precision    recall  f1-score   support

           0       0.71      0.52      0.60      1747
           1       0.66      0.82      0.73      2029

    accuracy                           0.68      3776
   macro avg       0.69      0.67      0.66      3776
weighted avg       0.68      0.68      0.67      3776

Confusion matrix:
 [[ 906  841]
 [ 375 1654]]

/opt/anaconda3/lib/python3.12/site-packages/numpy/ma/core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

In [85]:
from xgboost import XGBClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

X_final = X.copy()
y_final = y.copy()

cat_cols = X_final.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_final.select_dtypes(include=["number", "bool"]).columns.tolist()

final_preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])

final_xgb_model = Pipeline([
    ("prep", final_preprocessor),
    ("clf", XGBClassifier(
        objective="binary:logistic",
        eval_metric="auc",
        colsample_bytree=0.7,
        gamma=0.1,
        learning_rate=0.05,
        max_depth=5,
        min_child_weight=1,
        n_estimators=125,
        subsample=0.7,
        random_state=42,
        n_jobs=-1
    ))
])

final_xgb_model.fit(X_final, y_final)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['IndexYear', 'IndexMonth',
                                                   'IndexDayOfWeek',
                                                   'PatientBirthYearBin',
                                                   'DistanceMilesToIndexDept']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['IndexDepartmentName',
                                                   'IndexDepartmentSpecialty',
                                                   'IndexDepartmentCity',
                                                   'IndexDepartmentCounty',
                                                   'IndexVisitType',
                                                   'IndexVisitTypeDe...
                               feature_types=None, feature_weights=None,
                               gamma=0.1, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None, min_child_weight=1,
                               missing=nan, monotone_constraints=None,
                               multi_strategy=None, n_estimators=125, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [87]:
print("Best CV ROC AUC:", grid2.best_score_)

Best CV ROC AUC: 0.7289361019250272

In [89]:
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_model.select_dtypes(include=["number", "bool"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", SimpleImputer(strategy="median"), num_cols),
    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

rf_pipe = Pipeline([
    ("prep", preprocessor),
    ("clf", RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ))
])

param_grid = {
    "clf__n_estimators": [200, 400],
    "clf__max_depth": [None, 10, 20],
    "clf__min_samples_split": [2, 10],
    "clf__min_samples_leaf": [1, 5],
    "clf__max_features": ["sqrt", 0.5]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

rf_grid = GridSearchCV(
    estimator=rf_pipe,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

rf_grid.fit(X_train, y_train)

best_rf = rf_grid.best_estimator_

y_prob = best_rf.predict_proba(X_test)[:, 1]
y_pred = best_rf.predict(X_test)

print("Best params:", rf_grid.best_params_)
print("Best CV ROC AUC:", rf_grid.best_score_)
print("Test ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best params: {'clf__max_depth': 10, 'clf__max_features': 0.5, 'clf__min_samples_leaf': 1, 'clf__min_samples_split': 10, 'clf__n_estimators': 400}
Best CV ROC AUC: 0.7260953823451395
Test ROC AUC: 0.7244764876096824

Classification report:

              precision    recall  f1-score   support

           0       0.71      0.51      0.59      1747
           1       0.66      0.82      0.73      2029

    accuracy                           0.68      3776
   macro avg       0.69      0.67      0.66      3776
weighted avg       0.69      0.68      0.67      3776

Confusion matrix:
 [[ 891  856]
 [ 358 1671]]

In [90]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
cat_idx = [X_model.columns.get_loc(col) for col in cat_cols]

X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

cat_model = CatBoostClassifier(
    loss_function="Logloss",
    eval_metric="AUC",
    random_state=42,
    verbose=0
)

param_grid = {
    "depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "iterations": [200, 400],
    "l2_leaf_reg": [1, 3, 5]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cat_grid = GridSearchCV(
    estimator=cat_model,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

cat_grid.fit(
    X_train,
    y_train,
    cat_features=cat_idx
)

best_cat = cat_grid.best_estimator_

y_prob = best_cat.predict_proba(X_test)[:, 1]
y_pred = best_cat.predict(X_test)

print("Best params:", cat_grid.best_params_)
print("Best CV ROC AUC:", cat_grid.best_score_)
print("Test ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 54 candidates, totalling 270 fits
Best params: {'depth': 6, 'iterations': 400, 'l2_leaf_reg': 3, 'learning_rate': 0.03}
Best CV ROC AUC: 0.7283625766120048
Test ROC AUC: 0.7284352560454971

Classification report:

              precision    recall  f1-score   support

           0       0.71      0.52      0.60      1747
           1       0.66      0.81      0.73      2029

    accuracy                           0.68      3776
   macro avg       0.68      0.67      0.66      3776
weighted avg       0.68      0.68      0.67      3776

Confusion matrix:
 [[ 911  836]
 [ 381 1648]]

In [92]:
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
cat_idx = [X_model.columns.get_loc(col) for col in cat_cols]

X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

cat_model = CatBoostClassifier(
    loss_function="Logloss",
    eval_metric="AUC",
    random_state=42,
    verbose=0
)

param_grid = {
    "depth": [6],
    "iterations": [350, 400, 450],
    "learning_rate": [0.02, 0.03, 0.04],
    "l2_leaf_reg": [2, 3, 4]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cat_grid_2 = GridSearchCV(
    estimator=cat_model,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

cat_grid_2.fit(
    X_train,
    y_train,
    cat_features=cat_idx
)

best_cat_2 = cat_grid_2.best_estimator_

y_prob = best_cat_2.predict_proba(X_test)[:, 1]
y_pred = best_cat_2.predict(X_test)

print("Best params:", cat_grid_2.best_params_)
print("Best CV ROC AUC:", cat_grid_2.best_score_)
print("Test ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 27 candidates, totalling 135 fits
Best params: {'depth': 6, 'iterations': 450, 'l2_leaf_reg': 3, 'learning_rate': 0.03}
Best CV ROC AUC: 0.7284821970796329
Test ROC AUC: 0.7284420267878781

Classification report:

              precision    recall  f1-score   support

           0       0.71      0.52      0.60      1747
           1       0.66      0.81      0.73      2029

    accuracy                           0.68      3776
   macro avg       0.69      0.67      0.67      3776
weighted avg       0.68      0.68      0.67      3776

Confusion matrix:
 [[ 916  831]
 [ 381 1648]]

In [93]:
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_model.select_dtypes(include=["number", "bool"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]), num_cols),
    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

knn_pipe = Pipeline([
    ("prep", preprocessor),
    ("clf", KNeighborsClassifier())
])

param_grid = {
    "clf__n_neighbors": [5, 11, 21, 31],
    "clf__weights": ["uniform", "distance"],
    "clf__metric": ["euclidean", "manhattan"]
}

X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

knn_grid = GridSearchCV(
    estimator=knn_pipe,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

knn_grid.fit(X_train, y_train)

best_knn = knn_grid.best_estimator_

y_prob = best_knn.predict_proba(X_test)[:, 1]
y_pred = best_knn.predict(X_test)

print("Best params:", knn_grid.best_params_)
print("Best CV ROC AUC:", knn_grid.best_score_)
print("Test ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 16 candidates, totalling 80 fits
Best params: {'clf__metric': 'manhattan', 'clf__n_neighbors': 31, 'clf__weights': 'uniform'}
Best CV ROC AUC: 0.7051639138369193
Test ROC AUC: 0.7155794500069541

Classification report:

              precision    recall  f1-score   support

           0       0.67      0.55      0.61      1747
           1       0.67      0.77      0.71      2029

    accuracy                           0.67      3776
   macro avg       0.67      0.66      0.66      3776
weighted avg       0.67      0.67      0.66      3776

Confusion matrix:
 [[ 969  778]
 [ 473 1556]]

In [94]:
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix

X_model = X.copy()
y_model = y.copy()

cat_cols = X_model.select_dtypes(include=["object", "string", "category"]).columns.tolist()
num_cols = X_model.select_dtypes(include=["number", "bool"]).columns.tolist()

preprocessor = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]), num_cols),
    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_cols)
])

nn_pipe = Pipeline([
    ("prep", preprocessor),
    ("clf", MLPClassifier(
        max_iter=300,
        early_stopping=True,
        random_state=42
    ))
])

param_grid = {
    "clf__hidden_layer_sizes": [(64,), (128,), (64, 32)],
    "clf__alpha": [0.0001, 0.001, 0.01],
    "clf__learning_rate_init": [0.001, 0.01]
}

X_train, X_test, y_train, y_test = train_test_split(
    X_model,
    y_model,
    test_size=0.2,
    stratify=y_model,
    random_state=42
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

nn_grid = GridSearchCV(
    estimator=nn_pipe,
    param_grid=param_grid,
    scoring="roc_auc",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

nn_grid.fit(X_train, y_train)

best_nn = nn_grid.best_estimator_

y_prob = best_nn.predict_proba(X_test)[:, 1]
y_pred = best_nn.predict(X_test)

print("Best params:", nn_grid.best_params_)
print("Best CV ROC AUC:", nn_grid.best_score_)
print("Test ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification report:\n")
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 18 candidates, totalling 90 fits
Best params: {'clf__alpha': 0.0001, 'clf__hidden_layer_sizes': (64,), 'clf__learning_rate_init': 0.01}
Best CV ROC AUC: 0.7233694661779879
Test ROC AUC: 0.7248502890119597

Classification report:

              precision    recall  f1-score   support

           0       0.68      0.56      0.61      1747
           1       0.67      0.77      0.72      2029

    accuracy                           0.67      3776
   macro avg       0.67      0.67      0.67      3776
weighted avg       0.67      0.67      0.67      3776

Confusion matrix:
 [[ 972  775]
 [ 458 1571]]